// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3VNxl23_ijiLJuEl9oFXJoYpjFGU79xg',
    appId: '1:349191821542:web:c737bfa34ffc9cc88ec327',
    messagingSenderId: '349191821542',
    projectId: 'hungry-hutt-user',
    authDomain: 'hungry-hutt-user.firebaseapp.com',
    storageBucket: 'hungry-hutt-user.firebasestorage.app',
    measurementId: 'G-6RW7XFJ74G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6F3rNvltDn5UyIDnZZwYOSKveXf9ZOO8',
    appId: '1:349191821542:android:923ce55d6278f6358ec327',
    messagingSenderId: '349191821542',
    projectId: 'hungry-hutt-user',
    storageBucket: 'hungry-hutt-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoLbJZKvilWTfum688xZbdpnbod5iAvqY',
    appId: '1:349191821542:ios:12c56c1aae4da63f8ec327',
    messagingSenderId: '349191821542',
    projectId: 'hungry-hutt-user',
    storageBucket: 'hungry-hutt-user.firebasestorage.app',
    iosBundleId: 'com.hungryhutt.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoLbJZKvilWTfum688xZbdpnbod5iAvqY',
    appId: '1:349191821542:ios:12c56c1aae4da63f8ec327',
    messagingSenderId: '349191821542',
    projectId: 'hungry-hutt-user',
    storageBucket: 'hungry-hutt-user.firebasestorage.app',
    iosBundleId: 'com.hungryhutt.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3VNxl23_ijiLJuEl9oFXJoYpjFGU79xg',
    appId: '1:349191821542:web:b5367d45bb5140728ec327',
    messagingSenderId: '349191821542',
    projectId: 'hungry-hutt-user',
    authDomain: 'hungry-hutt-user.firebaseapp.com',
    storageBucket: 'hungry-hutt-user.firebasestorage.app',
    measurementId: 'G-JCLT9JH3L4',
  );
}
